# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://social-science-data-editors.github.io
title: Social Science Data Editors
email: your-email@domain.com
author: SSDE
description: > # "Write an awesome description for your new site here. 
  The Social Science Data Editors work to improve reproducibility and transparency in social science research.
copyright: 'Copyright &copy; 2024 Social Science Data Editors. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created from <a href="https://github.com/swcool">swcool</a>.'
logo: /assets/ssde-logo.jpeg


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    icon: github
    url: https://github.com/social-science-data-editors/

navigation:
  - title: DCAS
    url: /#dcas
  - title: README
    url: /#readme
  - title: Guidance
    url: /#guidance
  - title: Contact
    url: /#contact