# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://social-science-data-editors.github.io/
title: Social Science Data Editors
email: your-email@domain.com
author: SSDE
description: > # "Write an awesome description for your new site here. 
  The Social Science Data Editors work to improve reproducibility and transparency in social science research.
copyright: 'Copyright &copy; 2024 Social Science Data Editors. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created from <a href="https://github.com/swcool">swcool</a>.'
logo: /assets/ssde-logo.jpeg


# ----------------------- #
#  Stuff about the society#
# ----------------------- #

registration: (coming soon)
president:  John M. Abowd
treasurer: Alan Karr 
secretary: Alan Karr
board:
  - Jerome Reiter
  - Aleksandra Slavković

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: journal
    icon: newspaper-o
    url: https://journalprivacyconfidentiality.org/
  - title: github
    icon: github
    url: https://github.com/journalprivacyconfidentiality/

navigation:
  - title: Purpose
    url: /#purpose
  - title: Journal
    url: /#journal
  - title: Other
    url: /#tpdp
  - title: About
    url: /#contact